// <auto-generated />
using System;
using CarRentalApi.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarRentalApi.Migrations
{
    [DbContext(typeof(CarRentalContext))]
    [Migration("20190528111840_quick-fix")]
    partial class quickfix
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarRentalApi.Database.Model.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("ImageURL");

                    b.Property<double>("Price");

                    b.HasKey("Id");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Mercedes Benz with low price - 30.2 dollars per hour! Be quick offers are time limited! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Donec accumsan molestie risus vitae porta. Maecenas luctus imperdiet porttitor. Pellentesque vel dapibus mauris. Ut gravida velit non augue viverra, ut luctus odio iaculis. Proin enim ante, congue et viverra vulputate, congue.",
                            ImageURL = "https://images.pexels.com/photos/112460/pexels-photo-112460.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                            Price = 30.199999999999999
                        },
                        new
                        {
                            Id = 2,
                            Description = "Land Rover Range Rover Suv with low price - 42.3 dollars per hour! Be quick offers are time limited! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut eget risus vel nisl aliquam maximus sed vitae enim. Nam facilisis nec dui sed vulputate. Duis bibendum rutrum nunc in fringilla. Praesent et rhoncus libero. Sed vel interdum purus. Ut enim.",
                            ImageURL = "https://images.pexels.com/photos/116675/pexels-photo-116675.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
                            Price = 42.299999999999997
                        },
                        new
                        {
                            Id = 3,
                            Description = "Mercedes-Benz E220d SE Automatic 2.0 with price - 55 dollars per hour! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse lacinia metus a nibh molestie, a egestas metus egestas. Vestibulum ultricies neque suscipit porta tempor. Donec bibendum tempor bibendum. Morbi dapibus porta mattis. Integer dignissim dui at orci tincidunt ultricies eu.",
                            ImageURL = "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/2019_Mercedes-Benz_E220d_SE_Automatic_2.0_Front.jpg/800px-2019_Mercedes-Benz_E220d_SE_Automatic_2.0_Front.jpg",
                            Price = 55.0
                        },
                        new
                        {
                            Id = 4,
                            Description = "Mercedes-Benz CLS 350d with price - 60 dollars per hour! Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed id dui quis enim tincidunt ultrices. Phasellus vel condimentum quam, at volutpat ipsum. Quisque porttitor purus et justo mattis tempus. Etiam scelerisque ornare nibh, eget sagittis elit tristique non. Praesent pulvinar.",
                            ImageURL = "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Mercedes-Benz_CLS_350d_IMG_0901.jpg/800px-Mercedes-Benz_CLS_350d_IMG_0901.jpg",
                            Price = 60.0
                        });
                });

            modelBuilder.Entity("CarRentalApi.Database.Model.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Latitude = 51.757928,
                            Longitude = 19.434822,
                            Name = "Red Car Rental"
                        },
                        new
                        {
                            Id = 2,
                            Latitude = 51.769187000000002,
                            Longitude = 19.461393000000001,
                            Name = "Blue Car Rental"
                        },
                        new
                        {
                            Id = 3,
                            Latitude = 51.771438000000003,
                            Longitude = 19.458452999999999,
                            Name = "Yellow Car Rental"
                        },
                        new
                        {
                            Id = 4,
                            Latitude = 51.774113,
                            Longitude = 19.457691000000001,
                            Name = "Green Car Rental"
                        });
                });

            modelBuilder.Entity("CarRentalApi.Database.Model.Reservation", b =>
                {
                    b.Property<int>("ReservationNumber")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Age");

                    b.Property<int>("CarId");

                    b.Property<DateTime>("PickUpDate");

                    b.Property<int>("PickUpLocationId");

                    b.Property<DateTime>("ReturnDate");

                    b.Property<int>("ReturnLocationId");

                    b.Property<string>("Surname")
                        .IsRequired();

                    b.HasKey("ReservationNumber");

                    b.HasIndex("CarId");

                    b.HasIndex("PickUpLocationId");

                    b.HasIndex("ReturnLocationId");

                    b.HasIndex("ReservationNumber", "Surname")
                        .IsUnique();

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("CarRentalApi.Database.Model.Reservation", b =>
                {
                    b.HasOne("CarRentalApi.Database.Model.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("CarRentalApi.Database.Model.Location", "PickUpLocation")
                        .WithMany()
                        .HasForeignKey("PickUpLocationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CarRentalApi.Database.Model.Location", "ReturnLocation")
                        .WithMany()
                        .HasForeignKey("ReturnLocationId")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
